### ISSUE TITLE
Docusaurus 3.2.0 - Breaking Changes

### ISSUE THREAD

**Issue by Devon-White** [cloud-annotations/docusaurus-openapi#282]
In the latest Docusaurus upgrade, 3.2.0, a few things broke the plugin.

1. `addLeadingSlash` and `addTrailingSlash` were removed from `@docusaurus/utils` due to being a duplicate in `@docusaurus/utils-common`. PR can be found [here](https://github.com/facebook/docusaurus/pull/9949/files)
---
2. `PluginOptions` passing undefined values for `showLastUpdateTime` and `showLastUpdateAuthor` in the `options` property.

```
src/index.ts(87,13): error TS2739: Type 'PluginOptions' is missing the following properties from type 'Omit<MetadataOptions, "numberPrefixParser" | "editCurrentVersion" | "editLocalizedFiles" | "breadcrumbs">': showLastUpdateTime, showLastUpdateAuthor
```
---
3. cypress test fails due to sidebar collapsible menus now having the role of `button` instead of `link`. Items in the menu are still considered links however.

  (Results)

  
  │ Tests:        4 
  │ Passing:      3
  │ Failing:      1
  │ Pending:      0 
  │ Skipped:      0 
  │ Screenshots:  1  
  │ Video:        false
  │ Duration:     6 seconds                                                                      
  │ Spec Ran:     test.spec.ts                                                                  

``` 
AssertionError: Timed out retrying after 4000ms: Unable to find an accessible element with the role "link" and name `/^pet$/i`
```

**Comment by Devon-White** [comment]
Actions I took to get this working on Docusaurus 3.2.0:

- `addLeadingSlash` and `addTrailingSlash` imported now from `@docusaurus/utils-common`
- Omit `showLastUpdateAuthor` & `showLastUpdateTime` from PluginOptions 
- Edit to cypress test tonav() function due to certain links having the role of `button` instead of `link`.
- Updated plugin to use Docusaurus 3.2.0 packages
- Updated demo to run on docusaurus 3.2.0

**Comment by bourdakos1** [comment]
Thanks for filing such a thorough issue :) Would you mind opening a pull request with these fixes?
